### ISSUE TITLE
Error loading MIB file - v 0.3.0 (still with 0.2.0)

### ISSUE THREAD

**Issue by andreaconsadori** [Graylog2/graylog-plugin-snmp#4]
here the detail

2015-08-17T08:33:37.065+02:00 ERROR [SnmpMibsLoader] Error loading MIB file: /usr/share/mibs/ietf/RADIUS-ACC-CLIENT-MIB
java.lang.ArrayIndexOutOfBoundsException: 2048
        at net.percederberg.grammatica.parser.TokenNFA$StateQueue.addLast(TokenNFA.java:1309)
        at net.percederberg.grammatica.parser.TokenNFA$State.matchTransitions(TokenNFA.java:393)
        at net.percederberg.grammatica.parser.TokenNFA.match(TokenNFA.java:198)
        at net.percederberg.grammatica.parser.Tokenizer$NFAMatcher.match(Tokenizer.java:560)
        at net.percederberg.grammatica.parser.Tokenizer.nextToken(Tokenizer.java:328)
        at net.percederberg.grammatica.parser.Tokenizer.next(Tokenizer.java:287)
        at net.percederberg.grammatica.parser.Parser.peekToken(Parser.java:629)
        at net.percederberg.grammatica.parser.Parser.nextToken(Parser.java:566)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.throwParseException(RecursiveDescentParser.java:812)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parsePattern(RecursiveDescentParser.java:202)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseElement(RecursiveDescentParser.java:261)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseAlternative(RecursiveDescentParser.java:227)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parsePattern(RecursiveDescentParser.java:198)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseElement(RecursiveDescentParser.java:261)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseAlternative(RecursiveDescentParser.java:227)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parsePattern(RecursiveDescentParser.java:198)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseElement(RecursiveDescentParser.java:261)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseAlternative(RecursiveDescentParser.java:227)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parsePattern(RecursiveDescentParser.java:198)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseElement(RecursiveDescentParser.java:261)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseAlternative(RecursiveDescentParser.java:227)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parsePattern(RecursiveDescentParser.java:198)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseElement(RecursiveDescentParser.java:261)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseAlternative(RecursiveDescentParser.java:227)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parsePattern(RecursiveDescentParser.java:198)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseElement(RecursiveDescentParser.java:261)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseAlternative(RecursiveDescentParser.java:227)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parsePattern(RecursiveDescentParser.java:198)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseElement(RecursiveDescentParser.java:261)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseAlternative(RecursiveDescentParser.java:227)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parsePattern(RecursiveDescentParser.java:198)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseElement(RecursiveDescentParser.java:261)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseAlternative(RecursiveDescentParser.java:227)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parsePattern(RecursiveDescentParser.java:198)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseElement(RecursiveDescentParser.java:261)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseAlternative(RecursiveDescentParser.java:227)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parsePattern(RecursiveDescentParser.java:198)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseStart(RecursiveDescentParser.java:162)
        at net.percederberg.grammatica.parser.Parser.parse(Parser.java:394)
        at net.percederberg.mibble.MibLoader$MibSource.parseMib(MibLoader.java:972)
        at net.percederberg.mibble.MibLoader.loadQueue(MibLoader.java:724)
        at net.percederberg.mibble.MibLoader.load(MibLoader.java:550)
        at net.percederberg.mibble.MibLoader.load(MibLoader.java:479)
        at org.graylog.snmp.oid.SnmpMibsLoader.loadMibsFromPath(SnmpMibsLoader.java:80)
        at org.graylog.snmp.oid.SnmpMibsLoader.<init>(SnmpMibsLoader.java:35)
        at org.graylog.snmp.SnmpCommandResponder.<init>(SnmpCommandResponder.java:38)
        at org.graylog.snmp.codec.SnmpCodec.decode(SnmpCodec.java:61)
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:120)
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:79)
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:56)
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:33)
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:138)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

this is the mib
http://www.filedropper.com/radius-acc-client-mib

**Comment by andreaconsadori** [comment]
also i've another error, i've to open another ticket for this exception?

2015-08-17T08:41:31.110+02:00 ERROR [SnmpMibsLoader] Error loading MIB file: /usr/share/mibs/ietf/P-BRIDGE-MIB
java.lang.NullPointerException
        at net.percederberg.grammatica.parser.ReaderBuffer.ensureCapacity(ReaderBuffer.java:348)
        at net.percederberg.grammatica.parser.ReaderBuffer.ensureBuffered(ReaderBuffer.java:320)
        at net.percederberg.grammatica.parser.ReaderBuffer.peek(ReaderBuffer.java:222)
        at net.percederberg.grammatica.parser.TokenNFA.match(TokenNFA.java:173)
        at net.percederberg.grammatica.parser.Tokenizer$NFAMatcher.match(Tokenizer.java:560)
        at net.percederberg.grammatica.parser.Tokenizer.nextToken(Tokenizer.java:328)
        at net.percederberg.grammatica.parser.Tokenizer.next(Tokenizer.java:287)
        at net.percederberg.grammatica.parser.Parser.peekToken(Parser.java:629)
        at net.percederberg.grammatica.parser.Parser.nextToken(Parser.java:566)
        at net.percederberg.grammatica.parser.Parser.nextToken(Parser.java:594)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseElement(RecursiveDescentParser.java:257)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseAlternative(RecursiveDescentParser.java:227)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parsePattern(RecursiveDescentParser.java:198)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseElement(RecursiveDescentParser.java:261)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseAlternative(RecursiveDescentParser.java:227)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parsePattern(RecursiveDescentParser.java:198)
        at net.percederberg.grammatica.parser.RecursiveDescentParser.parseStart(RecursiveDescentParser.java:162)
        at net.percederberg.grammatica.parser.Parser.parse(Parser.java:394)
        at net.percederberg.mibble.MibLoader$MibSource.parseMib(MibLoader.java:972)
        at net.percederberg.mibble.MibLoader.loadQueue(MibLoader.java:724)
        at net.percederberg.mibble.MibLoader.load(MibLoader.java:550)
        at net.percederberg.mibble.MibLoader.load(MibLoader.java:479)
        at org.graylog.snmp.oid.SnmpMibsLoader.loadMibsFromPath(SnmpMibsLoader.java:80)
        at org.graylog.snmp.oid.SnmpMibsLoader.<init>(SnmpMibsLoader.java:35)
        at org.graylog.snmp.SnmpCommandResponder.<init>(SnmpCommandResponder.java:38)
        at org.graylog.snmp.codec.SnmpCodec.decode(SnmpCodec.java:61)
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:120)
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:79)
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:56)
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:33)
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:138)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by bernd** [comment]
Thanks for the report, we will try to reproduce that.

**Comment by bernd** [comment]
@andreaconsadori I am unable to reproduce that. :confused: I also have the `/usr/share/mibs/ietf/RADIUS-ACC-CLIENT-MIB` and `/usr/share/mibs/ietf/P-BRIDGE-MIB` files. (downloaded via the mibs downloader on Ubuntu)

Did you use the mibs downloader as well or do you got those files from somewhere else?

**Comment by andreaconsadori** [comment]
I've to check but i think they came from arubanetworks site because traps are generated from clearpass radius server


Inviato da Outlook per Android





On Wed, Oct 14, 2015 at 8:59 AM -0700, "Bernd Ahlers" <notifications@github.com> wrote:
@andreaconsadori I am unable to reproduce that. :confused: I also have the `/usr/share/mibs/ietf/RADIUS-ACC-CLIENT-MIB` and `/usr/share/mibs/ietf/P-BRIDGE-MIB` files. (downloaded via the mibs downloader on Ubuntu)

Did you use the mibs downloader as well or do you got those files from somewhere else?

---

**Comment by jonasblomq** [comment]
I keep getting the same errors for Cisco WLC MIBS.
2016-11-14T08:57:36.801+02:00 ERROR [SnmpMibsLoader] Error loading MIB file: /usr/share/snmp/mibs/CISCO-LWAPP-TC-MIB.my
java.lang.ArrayIndexOutOfBoundsException

Attatched a archive of all mibs I am loading.
Verified the loading order in mibble, and everything seems to work just fine there.

[mibs.zip](https://github.com/Graylog2/graylog-plugin-snmp/files/588586/mibs.zip)

**Comment by lucasevabou14** [comment]
Hello,

I have the same behaviour on CISCO-LWAPP-DOT11-CLIENT-MIB.my. 
Moreover the snmp traps are send by the WLC but I cannot see its on graylog snmp input although I see over snmp traps

Any feedback ?
