### ISSUE TITLE
Got the same issue, normal MIBS wont load

### ISSUE THREAD

**Issue by Jerrison777** [Graylog2/graylog-plugin-snmp#5]
I left the input to the default folder, getting the error message for every mib under /usr/share/snmp/mibs (just took Transport-Address as an example):

2015-08-26 16:11:24,023 ERROR: org.graylog.snmp.oid.SnmpMibsLoader - Error loading MIB file: /usr/share/snmp/mibs/TRANSPORT-ADDRESS-MIB.txt
java.lang.NullPointerException
	at net.percederberg.grammatica.parser.TokenNFA.match(TokenNFA.java:194)
	at net.percederberg.grammatica.parser.Tokenizer$NFAMatcher.match(Tokenizer.java:560)
	at net.percederberg.grammatica.parser.Tokenizer.nextToken(Tokenizer.java:328)
	at net.percederberg.grammatica.parser.Tokenizer.next(Tokenizer.java:287)
	at net.percederberg.grammatica.parser.Parser.peekToken(Parser.java:629)
	at net.percederberg.grammatica.parser.LookAheadSet$Sequence.isNext(LookAheadSet.java:750)
	at net.percederberg.grammatica.parser.LookAheadSet.isNext(LookAheadSet.java:184)
	at net.percederberg.grammatica.parser.RecursiveDescentParser.isNext(RecursiveDescentParser.java:286)
	at net.percederberg.grammatica.parser.RecursiveDescentParser.isNext(RecursiveDescentParser.java:329)
	at net.percederberg.grammatica.parser.RecursiveDescentParser.parseElement(RecursiveDescentParser.java:255)
	at net.percederberg.grammatica.parser.RecursiveDescentParser.parseAlternative(RecursiveDescentParser.java:227)
	at net.percederberg.grammatica.parser.RecursiveDescentParser.parsePattern(RecursiveDescentParser.java:198)
	at net.percederberg.grammatica.parser.RecursiveDescentParser.parseElement(RecursiveDescentParser.java:261)
	at net.percederberg.grammatica.parser.RecursiveDescentParser.parseAlternative(RecursiveDescentParser.java:227)
	at net.percederberg.grammatica.parser.RecursiveDescentParser.parsePattern(RecursiveDescentParser.java:198)
	at net.percederberg.grammatica.parser.RecursiveDescentParser.parseElement(RecursiveDescentParser.java:261)
	at net.percederberg.grammatica.parser.RecursiveDescentParser.parseAlternative(RecursiveDescentParser.java:227)
	at net.percederberg.grammatica.parser.RecursiveDescentParser.parsePattern(RecursiveDescentParser.java:198)
	at net.percederberg.grammatica.parser.RecursiveDescentParser.parseElement(RecursiveDescentParser.java:261)
	at net.percederberg.grammatica.parser.RecursiveDescentParser.parseAlternative(RecursiveDescentParser.java:227)
	at net.percederberg.grammatica.parser.RecursiveDescentParser.parsePattern(RecursiveDescentParser.java:198)
	at net.percederberg.grammatica.parser.RecursiveDescentParser.parseStart(RecursiveDescentParser.java:162)
	at net.percederberg.grammatica.parser.Parser.parse(Parser.java:394)
	at net.percederberg.mibble.MibLoader$MibSource.parseMib(MibLoader.java:972)
	at net.percederberg.mibble.MibLoader.loadQueue(MibLoader.java:724)
	at net.percederberg.mibble.MibLoader.load(MibLoader.java:550)
	at net.percederberg.mibble.MibLoader.load(MibLoader.java:479)
	at org.graylog.snmp.oid.SnmpMibsLoader.loadMibsFromPath(SnmpMibsLoader.java:80)
	at org.graylog.snmp.oid.SnmpMibsLoader.<init>(SnmpMibsLoader.java:36)
	at org.graylog.snmp.SnmpCommandResponder.<init>(SnmpCommandResponder.java:38)
	at org.graylog.snmp.codec.SnmpCodec.decode(SnmpCodec.java:61)
	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:120)
	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:79)
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:56)
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:33)
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:138)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Using 0.3.0 and latest graylog 1.1.6.

**Comment by bernd** [comment]
I am unable to reproduce this with the 0.3.0 plugin. I am using the snmp-mibs-downloader on Ubuntu to download all the mibs. How do you download them?

**Comment by Jerrison777** [comment]
Ill upload the mib tomorrow. Iirc I tried the mibs already provided with the net-snmp package and tried a 'barebone' approach which still resulted in the errors described above.

**Comment by andral** [comment]
We have the same issue with graylog 1.0.1, plugin 0.3.0 and rhel7.
MIBs come from net-snmp-libs-5.7.2-20.el7_1.1.x86_64
Haven't touched the defaults of the input, e.g. no custom mib directory added.

2015-10-20T15:49:50.059+02:00 WARN  [SnmpMibsLoader] Error parsing MIB file: /usr/share/snmp/mibs/TUNNEL-MIB.txt
 - unexpected token "for" <IDENTIFIER_STRING>, expected "FROM"


 # java -version
java version "1.7.0_85"
OpenJDK Runtime Environment (rhel-2.6.1.2.el7_1-x86_64 u85-b01)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)

**Comment by waltdjr** [comment]
I'm having the same problems using the latest GL2 OVA in VMware with plugin 0.3.0.

The only mibs I currently have are the iana and ietf mibs that are pulled down from running the download-mibs command.

This is how it starts but it does this for almost if not all of the mibs:
` 2015-11-10_15:59:10.86183 INFO  [SnmpCommandResponder] Initialize new SnmpMibsLoader (custom path: "null")
2015-11-10_15:59:10.87035 INFO  [SnmpCommandResponder] Initialize new SnmpMibsLoader (custom path: "null")
2015-11-10_15:59:11.39128 ERROR [SnmpMibsLoader] Error loading MIB file: /usr/share/mibs/iana/IANA-FINISHER-MIB
2015-11-10_15:59:11.39132 java.lang.NullPointerException
2015-11-10_15:59:11.39133       at net.percederberg.grammatica.parser.Tokenizer.next(Tokenizer.java:296)
2015-11-10_15:59:11.39134       at net.percederberg.grammatica.parser.Parser.peekToken(Parser.java:629)
2015-11-10_15:59:11.39134       at net.percederberg.grammatica.parser.Parser.nextToken(Parser.java:566)
2015-11-10_15:59:11.39135       at net.percederberg.grammatica.parser.RecursiveDescentParser.parseAlternative(RecursiveDescentParser.java:230)
2015-11-10_15:59:11.39135       at net.percederberg.grammatica.parser.RecursiveDescentParser.parsePattern(RecursiveDescentParser.java:198)
2015-11-10_15:59:11.39136       at net.percederberg.grammatica.parser.RecursiveDescentParser.parseElement(RecursiveDescentParser.java:261)
2015-11-10_15:59:11.39137       at net.percederberg.grammatica.parser.RecursiveDescentParser.parseAlternative(RecursiveDescentParser.java:227)
2015-11-10_15:59:11.39137       at net.percederberg.grammatica.parser.RecursiveDescentParser.parsePattern(RecursiveDescentParser.java:198)
2015-11-10_15:59:11.39138       at net.percederberg.grammatica.parser.RecursiveDescentParser.parseStart(RecursiveDescentParser.java:162)
2015-11-10_15:59:11.39141       at net.percederberg.grammatica.parser.Parser.parse(Parser.java:394)
2015-11-10_15:59:11.39142       at net.percederberg.mibble.MibLoader$MibSource.parseMib(MibLoader.java:972)
2015-11-10_15:59:11.39143       at net.percederberg.mibble.MibLoader.loadQueue(MibLoader.java:724)
2015-11-10_15:59:11.39143       at net.percederberg.mibble.MibLoader.load(MibLoader.java:550)
2015-11-10_15:59:11.39144       at net.percederberg.mibble.MibLoader.load(MibLoader.java:479)
2015-11-10_15:59:11.39144       at org.graylog.snmp.oid.SnmpMibsLoader.loadMibsFromPath(SnmpMibsLoader.java:80)
2015-11-10_15:59:11.39144       at org.graylog.snmp.oid.SnmpMibsLoader.<init>(SnmpMibsLoader.java:35)
2015-11-10_15:59:11.39145       at org.graylog.snmp.SnmpCommandResponder.<init>(SnmpCommandResponder.java:38)
2015-11-10_15:59:11.39145       at org.graylog.snmp.codec.SnmpCodec.decode(SnmpCodec.java:61)
2015-11-10_15:59:11.39145       at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:136)
2015-11-10_15:59:11.39146       at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:82)
2015-11-10_15:59:11.39146       at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:58)
2015-11-10_15:59:11.39146       at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35)
2015-11-10_15:59:11.39147       at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:138)
2015-11-10_15:59:11.39148       at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
2015-11-10_15:59:11.39148       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2015-11-10_15:59:11.39149       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2015-11-10_15:59:11.39149       at java.lang.Thread.run(Thread.java:745)
2015-11-10_15:59:11.41515 WARN  [SnmpMibsLoader] Error parsing MIB file: /usr/share/mibs/iana/IANA-ADDRESS-FAMILY-NUMBERS-MIB
2015-11-10_15:59:11.41517  - unexpected token "DEFINITIONS", expected <IDENTIFIER_STRING>
2015-11-10_15:59:11.41519
2015-11-10_15:59:11.41713 ERROR [SnmpMibsLoader] Error loading MIB file: /usr/share/mibs/iana/IANA-FINISHER-MIB
2015-11-10_15:59:11.41715 java.lang.NullPointerException
2015-11-10_15:59:11.41716       at net.percederberg.grammatica.parser.ReaderBuffer.ensureCapacity(ReaderBuffer.java:348)
2015-11-10_15:59:11.41716       at net.percederberg.grammatica.parser.ReaderBuffer.ensureBuffered(ReaderBuffer.java:320)
2015-11-10_15:59:11.41717       at net.percederberg.grammatica.parser.ReaderBuffer.peek(ReaderBuffer.java:222)
2015-11-10_15:59:11.41717       at net.percederberg.grammatica.parser.TokenStringDFA.match(TokenStringDFA.java:114)
2015-11-10_15:59:11.41718       at net.percederberg.grammatica.parser.Tokenizer$StringDFAMatcher.match(Tokenizer.java:507)
2015-11-10_15:59:11.41718       at net.percederberg.grammatica.parser.Tokenizer.nextToken(Tokenizer.java:327)
2015-11-10_15:59:11.41718       at net.percederberg.grammatica.parser.Tokenizer.next(Tokenizer.java:287)
2015-11-10_15:59:11.41719       at net.percederberg.grammatica.parser.Parser.peekToken(Parser.java:629)
`

Let me know if you would like me to test anything for you.

Thanks,
WaltDjr

**Comment by aanriot** [comment]
Hello,

As discussed with Bernd, I have the same issue with Graylog 1.3 on Debian Jessie.

It occurs will several vendor's MIBs such as Dell and Cisco.

**Comment by gosse** [comment]
Hi - 

I'm having the same issue, with Juniper MIBs. graylog on CentOS. Any updates on this issue?
